export enum UserStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum UserType {
  ADMIN_STAFF = 'ADMIN_STAFF',
  MIDDLE_MANAGER = 'MIDDLE_MANAGER',
  GENERAL_HQ_MANAGER = 'GENERAL_HQ_MANAGER',
  DEPARTMENT_MANAGER = 'DEPARTMENT_MANAGER',
  TEAM_LEADER = 'TEAM_LEADER',
  SALES_STAFF = 'SALES_STAFF',
  REAL_ESTATE = 'REAL_ESTATE',
  PARTNER_STAFF = 'PARTNER_STAFF',
}

export enum CustomerStatus {
  REGISTERED = 'REGISTERED',
  VISITED = 'VISITED',
  CONSULTED = 'CONSULTED',
  CONTRACTED = 'CONTRACTED',
  CANCELLED = 'CANCELLED',
}
